//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class AN_CLCurve
    {
        public int InfoID { get; set; }
        public Nullable<double> Coeff_LV3 { get; set; }
        public Nullable<double> Coeff_LV2 { get; set; }
        public Nullable<double> Coeff_LV1 { get; set; }
        public Nullable<double> Const { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual MBR_Info MBR_Info { get; set; }
    }
    
}
