//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class AN_NetInfo
    {
        public int PoolID { get; set; }
        public string Matrix1 { get; set; }
        public Nullable<System.DateTime> UpdateTime1 { get; set; }
        public string Matrix2 { get; set; }
        public Nullable<System.DateTime> UpdateTime2 { get; set; }
        public string Matrix3 { get; set; }
        public Nullable<System.DateTime> UpdateTime3 { get; set; }
    
        public virtual MBR_Pool MBR_Pool { get; set; }
    }
    
}
