//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class DATADICTIONARYDETAIL
    {
        public DATADICTIONARYDETAIL()
        {
            this.DATADICTIONARYDETAIL1 = new HashSet<DATADICTIONARYDETAIL>();
        }
    
        public int DATADICTIONARYDETAILID { get; set; }
        public Nullable<int> DATADICTIONARYID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string CODE { get; set; }
        public string FULLNAME { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<int> SORTCODE { get; set; }
        public Nullable<int> DELETEMARK { get; set; }
    
        public virtual DATADICTIONARY DATADICTIONARY { get; set; }
        public virtual ICollection<DATADICTIONARYDETAIL> DATADICTIONARYDETAIL1 { get; set; }
        public virtual DATADICTIONARYDETAIL DATADICTIONARYDETAIL2 { get; set; }
    }
    
}
