//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class DATADICTIONARY
    {
        public DATADICTIONARY()
        {
            this.DATADICTIONARY1 = new HashSet<DATADICTIONARY>();
            this.DATADICTIONARYDETAIL = new HashSet<DATADICTIONARYDETAIL>();
        }
    
        public int DATADICTIONARYID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<int> ISTREE { get; set; }
        public string CATEGORY { get; set; }
        public string CODE { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> ENABLED { get; set; }
        public Nullable<int> SORTCODE { get; set; }
        public Nullable<int> DELETEMARK { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<DATADICTIONARY> DATADICTIONARY1 { get; set; }
        public virtual DATADICTIONARY DATADICTIONARY2 { get; set; }
        public virtual ICollection<DATADICTIONARYDETAIL> DATADICTIONARYDETAIL { get; set; }
    }
    
}
