//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class Knowlege
    {
        public int KnowlegeID { get; set; }
        public string Title { get; set; }
        public string KeyWords { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string AllContent { get; set; }
        public string Summary { get; set; }
    }
    
}
