//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class MBR_Info
    {
        public MBR_Info()
        {
            this.MBR_WashingInfo = new HashSet<MBR_WashingInfo>();
        }
    
        public int InfoID { get; set; }
        public Nullable<int> PoolID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string Company { get; set; }
        public string Model { get; set; }
        public string Title { get; set; }
    
        public virtual AN_CLCurve AN_CLCurve { get; set; }
        public virtual AN_HighCurve AN_HighCurve { get; set; }
        public virtual AN_LowCurve AN_LowCurve { get; set; }
        public virtual ICollection<MBR_WashingInfo> MBR_WashingInfo { get; set; }
        public virtual MBR_Pool MBR_Pool { get; set; }
    }
    
}
