//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class MBR_RunningInfo
    {
        public int RunningInfoID { get; set; }
        public Nullable<int> PoolID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<double> ChanShuiLL { get; set; }
        public Nullable<double> ChanShuiYL { get; set; }
        public Nullable<double> DanChiMCXQL { get; set; }
        public Nullable<double> WuNiND { get; set; }
        public Nullable<double> RongJieY { get; set; }
        public Nullable<double> KuaMoYC { get; set; }
        public Nullable<double> TouShuiL { get; set; }
        public Nullable<double> QiShuiB { get; set; }
        public Nullable<double> ShuiWen { get; set; }
        public Nullable<double> WenDuJZTSL { get; set; }
    
        public virtual MBR_Pool MBR_Pool { get; set; }
    }
    
}
