//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class MBR_Pool
    {
        public MBR_Pool()
        {
            this.MBR_Info = new HashSet<MBR_Info>();
            this.MBR_RunningInfo = new HashSet<MBR_RunningInfo>();
            this.MBR_WashingInfo = new HashSet<MBR_WashingInfo>();
        }
    
        public int PoolID { get; set; }
        public string PoolName { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual AN_NetInfo AN_NetInfo { get; set; }
        public virtual ICollection<MBR_Info> MBR_Info { get; set; }
        public virtual ICollection<MBR_RunningInfo> MBR_RunningInfo { get; set; }
        public virtual ICollection<MBR_WashingInfo> MBR_WashingInfo { get; set; }
    }
    
}
