//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class MBR_WashingInfo
    {
        public int WashingInfoID { get; set; }
        public Nullable<int> InfoID { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> WashType { get; set; }
        public Nullable<int> YaoJiLX { get; set; }
        public Nullable<double> JinPaoSJ { get; set; }
        public Nullable<double> YaoJiND { get; set; }
        public Nullable<double> TouShuiL_Low { get; set; }
        public Nullable<double> TouShuiL_High { get; set; }
        public Nullable<double> LvJieCZDC { get; set; }
    
        public virtual MBR_Info MBR_Info { get; set; }
    }
    
}
