//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class Module
    {
        public Module()
        {
            this.ModulePermission = new HashSet<ModulePermission>();
            this.Module1 = new HashSet<Module>();
        }
    
        public int ModuleID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FullName { get; set; }
        public string Code { get; set; }
        public string Location { get; set; }
        public string Target { get; set; }
        public string Icon { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> Isexpand { get; set; }
    
        public virtual ICollection<ModulePermission> ModulePermission { get; set; }
        public virtual ICollection<Module> Module1 { get; set; }
        public virtual Module Module2 { get; set; }
    }
    
}
