//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class ModulePermission
    {
        public int ModulePermissionID { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> ModuleID { get; set; }
    
        public virtual Module Module { get; set; }
    }
    
}
