//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class Role
    {
        public Role()
        {
            this.User = new HashSet<User>();
        }
    
        public int RoleID { get; set; }
        public Nullable<int> Category { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
    
}
