//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class SYS_RuningParam
    {
        public int RuningParamID { get; set; }
        public Nullable<int> PoolID { get; set; }
        public string ChanShuiLL { get; set; }
        public string ChanShuiYL { get; set; }
        public string DanChiMCXQL { get; set; }
        public string WuNiND { get; set; }
        public string RongJieY { get; set; }
        public string KuaMoYC { get; set; }
        public string TouShuiL { get; set; }
        public string QiShuiB { get; set; }
        public string ShuiWen { get; set; }
        public string WenDuJZTSL { get; set; }
    
        public virtual MBR_Pool MBR_Pool { get; set; }
    }
    
}
