//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class SYS_PoisonPump
    {
        public int PoisonPumpID { get; set; }
        public int PoolID { get; set; }
        public string PP_Name { get; set; }
        public Nullable<bool> PP_Type { get; set; }
        public string Status_Code { get; set; }
        public string V_Code { get; set; }
        public string Pos_Code { get; set; }
    
        public virtual MBR_Pool MBR_Pool { get; set; }
    }
    
}
