//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class User
    {
        public User()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
    }
    
}
