//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class WN_ParamSett
    {
        public int ParamSetID { get; set; }
        public Nullable<int> WarningCondID { get; set; }
        public string ParamID { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<int> WaitTime { get; set; }
    
        public virtual WN_WarningCond WN_WarningCond { get; set; }
    }
    
}
