//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class WN_WarningSett
    {
        public WN_WarningSett()
        {
            this.WN_WarningCond = new HashSet<WN_WarningCond>();
            this.WN_WarningLog = new HashSet<WN_WarningLog>();
        }
    
        public int WarningSettID { get; set; }
        public string Title { get; set; }
        public Nullable<int> WarningLevel { get; set; }
        public string WarningInfo { get; set; }
    
        public virtual WarningStat WarningStat { get; set; }
        public virtual ICollection<WN_WarningCond> WN_WarningCond { get; set; }
        public virtual ICollection<WN_WarningLog> WN_WarningLog { get; set; }
    }
    
}
