//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class WN_WarningCond
    {
        public WN_WarningCond()
        {
            this.WN_ParamSett = new HashSet<WN_ParamSett>();
        }
    
        public int WarningCondID { get; set; }
        public Nullable<int> WarningSettID { get; set; }
        public string WarningCondDesc { get; set; }
    
        public virtual ICollection<WN_ParamSett> WN_ParamSett { get; set; }
        public virtual WN_WarningSett WN_WarningSett { get; set; }
    }
    
}
