//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MBR.Models
{
    public partial class WN_WarningLog
    {
        public int WarningLogID { get; set; }
        public Nullable<int> WarningSettID { get; set; }
        public string WarningDesc { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Begin { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public int PoolID { get; set; }
    
        public virtual MBR_Pool MBR_Pool { get; set; }
        public virtual WN_WarningSett WN_WarningSett { get; set; }
    }
    
}
